services:
  postgres:
    image: postgres:13
    container_name: mp_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metropulse_dwh
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../stanging.sql:/docker-entrypoint-initdb.d/01-staging.sql
      - ../core_dwh.sql:/docker-entrypoint-initdb.d/02-core-dwh.sql
      - ../facts_core_dwh.sql:/docker-entrypoint-initdb.d/03-facts-dwh.sql

  minio:
    image: minio/minio
    container_name: mp_minio
    ports:
      - "9005:9000" # API port
      - "9001:9001" # console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: mp_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: mp_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: mp_clickhouse
    ports:
      - "8123:8123" # HTTP
      - "9002:9000" # Native
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ch_data:/var/lib/clickhouse

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mp_spark_master
    hostname: spark-master
    user: root
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - HOME=/home/spark
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=raw-data
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DB=metropulse_dwh
      - PG_USER=user
      - PG_PASSWORD=password
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./etl:/opt/spark/etl
      - spark_ivy_cache:/home/spark/.ivy2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mp_spark_worker
    user: root
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
      - HOME=/home/spark
      - SPARK_MASTER_URL=spark://spark-master:7077
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=raw-data
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DB=metropulse_dwh
      - PG_USER=user
      - PG_PASSWORD=password
    volumes:
      - ./etl:/opt/spark/etl
      - spark_ivy_cache:/home/spark/.ivy2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

volumes:
  pg_data:
  minio_data:
  ch_data:
  spark_ivy_cache: